<?php
/**
 * @version   1.7.0.2 August 7, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Overrides template/catalog/navigation/top.phtml
 */
?>

<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready( function() {
    $j(document).magemenus({
    mm_trigger: "ul.menu-single",
    mm_slidedownspeed: 250,mm_slideupspeed: 150,mm_css_pre: {left: 100, opacity: 0 },mm_animatein: {left: 165, opacity: 1},mm_animateout: {opacity: 0, left: 180},mm_animate_speed: 200,mm_pause: 200 }); 
}); 
</script>
<div id="box"><div class="head"></div></div>
<ul id="magemenu-top" class="menu-single">

    <li id="Home"><a href="<?php echo $this->getUrl('') ?>"><?php echo $this->__('Home') ?></a></li>

    <?php echo $this->renderCategoriesMenuHtml(0,'level-top'); ?>

    <li id="Contact"><a href="<?php echo $this->getUrl('contacts') ?>"><?php echo $this->__('Contact') ?></a></li>

</ul>