<?php
/**
 * @version   1.7.0.2 August 7, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 * Overrides template/catalog/product/view/media.phtml - removes default zoom and replaces with jquery version
 */
?>

<?php
$_product = $this->getProduct();
$_productNameStripped = $this->stripTags($_product->getName(), null, true);
$_helper = $this->helper('catalog/output');
?>

<?php
$panelId = 1;
?>

<?php
// Get small image width
$smallwidth = 300;
// Get small image height
$smallheight = 300;
// Get Large image width
$largewidth = 900;
// Get Large image height
$largeheight = 900;
// Get Thumbnail image width
$thumbnailwidth = 75;
// Get Thumbnail image height
$thumbnailheight = 75;
// Check if Zoom is ON
$zoom = 0;
// Check if Thumb Overlay is enabled
$overlaythumbs = 1;
// bg sizes
$bgwidth = $smallwidth + (($smallwidth / 100) * 8.2);
$bgheight = $smallheight + (($smallheight / 100) * 18);
?>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(function() {
        $j(".zoomer").miniZoomPan({ });
        $j('.product-shop .no-rating, .product-shop .ratings').remove(); // Hide these as we add them via product-view-media
    });
    var imgSmallWidth = <?php echo $smallwidth ?>;
    var imgSmallHeight = <?php echo $smallheight ?>;
    var imgWidth = <?php echo $largewidth ?>;
    var imgHeight = <?php echo $largeheight ?>;
</script>

<div class="rokmage-product-img-box" style="width:<?php echo round($smallwidth + (($smallwidth / 10))) ?>px;">
<div class="zoomer-product-pics">
    <div class="hovertozoom"><?php echo $this->__('Click main image to zoom &amp; pan') ?></div>
    <div id="zoomable" class="rounded_bg" style="width:<?php echo round($smallwidth + (($smallwidth / 100) * 1.6)) ?>px;height:<?php echo round($smallheight + (($smallheight / 100) * 14)) ?>px;padding:<?php echo round($bgwidth *= 0.032) ?>px;">
        <div class="photo-container" style="width:<?php echo $smallwidth +1 ?>px;height:<?php echo $smallheight ?>px;">
            <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <div id="photo_1" class="zoomer"><img id="productImgDefault" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($largewidth,$largeheight); ?>" alt="<?php echo $_productNameStripped ?>" /></div>
            <?php else: ?>
        <div id="photo_1" class="zoomer"><img id="productImgDefault" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($largewidth,$largeheight); ?>" alt="<?php echo $_productNameStripped ?>" /></div>
            <?php endif; ?>

            <?php foreach ($this->getGalleryImages() as $_image): $panelId++; ?>
        <div id="photo_<?php echo $panelId; ?>" style="display:none;" class="zoomer"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($largewidth,$largeheight); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></div>
            <?php endforeach; $panelId++; ?>
        
        <?php if ($overlaythumbs == 1): // Add thumbnails overlay ?>
        <?php
        $panelId2 = 1;
        $panelIdtotal = $panelId -1;
        ?>
            <?php if (count($this->getGalleryImages()) <= 0): ?>
            <?php else: ?>
        <div class="thumbswrapper" style="width:<?php echo $smallwidth ?>px;">
            <div class="thumbsbutton" style="width:<?php echo $smallwidth -23 ?>px;"><a href="javascript:void(0)"><?php echo $this->__('More images') ?></a></div>
            <div class="thumbsviewer">
                <ul class="thumbs">
                            <?php if (count($this->getGalleryImages()) > 0): ?>
                        <?php foreach ($this->getGalleryImages() as $_image): $panelId2++; ?>
            <li style="width:<?php echo $thumbnailwidth ?>px;height:<?php echo $thumbnailheight ?>px"><a class="zoomhover" href="javascript:void(0)" onclick="switch_product_img('photo_<?php echo $panelId2; ?>', <?php echo $panelIdtotal; ?>);"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($thumbnailwidth,$thumbnailheight); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a></li>
                        <?php endforeach; $panelId2++; ?>
                    <?php endif; ?>
                </ul>
                <div class="clearfloat"></div>
            </div>
        </div>
            <?php endif; ?>
        <?php endif; ?>
        
        <div class="review-box" style="top:<?php echo round($smallheight + ($smallheight / 25)) ?>px;"><?php echo $this->getReviewsSummaryHtml($_product, false, true)?></div>
        </div>
    </div>

        <script type="text/javascript">
            var $j = jQuery.noConflict();
            // Add our thumbnail zoom effect on hover
            $j(document).ready(function() {
                $j('a.zoomhover img').hover(function() { //mouse in
                    $j(this).stop().animate({ width: "110%"}, 100);
                }, function() { //mouse out
                    $j(this).stop().animate({ width: "100%"}, 300);
                });
                // Adjust width of info depending on size of image
                $space = $j('div.col-main').width();
                $used = $j('div.rokmage-product-img-box').width()
                $available = $space - $used - 15;
                $j('div.product-shop').css({ "width": $available });
                <?php if ($overlaythumbs == 1): // If showing thumbnails overlay ?>
                // Add our slide up thumbnail viewer
                $j(".thumbsbutton").click(function(){
                    $j(".thumbsviewer").slideToggle();
                    $j(".thumbsbutton").toggleClass("show");
                });
                <?php endif; ?>
            });
        </script>

        </div>
</div>