<?php
/**
 * @version   1.7.0.2 August 7, 2012
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
?>

<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>



<div id="footer-bottom">
        <?php $_links = $this->getLinks(); ?>
        <?php if (count($_links) > 0): ?>

        <script type="text/javascript">//<![CDATA[
            var $j = jQuery.noConflict();
            $j(document).ready(function(){
                var cartcount = $j('.rokmage-cart-box-container span.big').html();
                if(cartcount == 0) {
                    // Do Nothing
                } else {
                    if(cartcount == 1) {
                        $j('.footermenu li:eq(0)').html("<a href=\"<?php echo $this->getUrl('checkout/cart') ?>\" class=\"footercart\"><?php echo $this->__('Cart') ?> (<strong>1</strong> <?php echo $this->__('item') ?>)</a>");
                    } else {
                        $j('.footermenu li:eq(0)').html("<a href=\"<?php echo $this->getUrl('checkout/cart') ?>\" class=\"footercart\"><?php echo $this->__('Cart') ?> (<strong>" + cartcount + "</strong> <?php echo $this->__('items') ?>)</a>");
                    };
                };
            }); //]]>
        </script>

        <ul class="footermenu">
            <li><span><?php echo $this->__('Cart') ?> (<strong>0</strong> <?php echo $this->__('items') ?>)</span></li>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
    <?php $_links = $this->getLinks(); ?>
    <?php foreach ($_links as $_link): ?>
        <?php if ($_link instanceof Mage_Core_Block_Abstract): ?>
            <?php echo $_link->toHtml() ?>
        <?php else: ?>
                    <li<?php if ($_link->getIsFirst() || $_link->getIsLast()): ?> class="<?php if ($_link->getIsFirst()): ?>first<?php endif; ?><?php if ($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
        </ul>
<?php endif; ?>
</div>

<script type="text/javascript">
    jQuery(document).ready(function(){
jQuery('a.footercart').rokmagemodal({ rokmagemodalcontainer: "#rokmage-header-cart", overlayopacity: 0.2,overlayinspeed: 300,modalpreposition: {"top":"43%"},modalpauseb4entry: 200,modalentryanimation: {"top": "50%", "opacity": "1"},modalentryspeed: 550,modalexitanimation: {"top": "55%", "opacity": "0"},modalexitspeed: 350,pauseb4overlayfadeout: 500,overlayoutspeed: 200 });
}); 
</script>